import { EventDetail, GalleryPhoto, BankAccount, Wish, VideoConfig, CoupleData, DressCodeConfig, DressCodeColor } from '../types';

// Built-in illustrations and media, served from public/assets (generated by
// scripts/generate-doodle-assets.py, generate-music-box.py and
// render-story-video.cjs).
export const DOODLE_ASSETS = {
  floralEnvelope: '/assets/doodle/floral-envelope.svg',
};

export const DEFAULT_AUDIO_URL = '/assets/music/canon-in-d-music-box.mp3';
export const DEFAULT_VIDEO_URL = '/assets/video/our-story.webm';
export const DEFAULT_GROOM_IMAGE = '/assets/couple/groom.svg';
export const DEFAULT_BRIDE_IMAGE = '/assets/couple/bride.svg';

export const COUPLE_DATA: CoupleData = {
  groom: {
    name: 'Arga Pratama Wijaya',
    nickname: 'Arga',
    role: 'Putra Pertama dari Bapak Surya Wijaya & Ibu Ratih Purnamasari',
    instagram: 'argapratama',
    image: DEFAULT_GROOM_IMAGE,
    alt: 'Arga Pratama Wijaya',
  },
  bride: {
    name: 'Kirana Maharani Putri',
    nickname: 'Kirana',
    role: 'Putri Kedua dari Bapak Dimas Hartono & Ibu Lestari Handayani',
    instagram: 'kiranamaharani',
    image: DEFAULT_BRIDE_IMAGE,
    alt: 'Kirana Maharani Putri',
  },
  weddingDate: 'Minggu, 14 Februari 2027',
  weddingCity: 'Bandung',
  targetTimestamp: new Date('2027-02-14T09:00:00+07:00').getTime(),
  audioUrl: DEFAULT_AUDIO_URL,
  audioTitle: 'Canon in D (Music Box)',
  loveStory: [
    {
      id: 'story-1',
      stepNumber: 1,
      label: 'Awal Cerita',
      title: 'Pertama kali bertemu',
      text: 'Kisah kami dimulai tanpa rencana. Sebuah perkenalan membawa kami pada banyak percakapan, pertemuan, dan momen sederhana yang perlahan terasa istimewa.',
    },
    {
      id: 'story-2',
      stepNumber: 2,
      label: 'Lamaran',
      title: 'Menjalin cerita',
      text: 'Setelah melewati berbagai perjalanan bersama, kami semakin yakin untuk membawa hubungan ini menuju masa depan. Di hadapan keluarga, kami menyampaikan niat dan mengikat komitmen untuk melangkah bersama.',
    },
    {
      id: 'story-3',
      stepNumber: 3,
      label: 'Pernikahan',
      title: 'Menuju babak baru',
      text: 'Dengan penuh syukur, kami tiba pada awal perjalanan baru. Bukan sebagai akhir dari kisah cinta, tetapi sebagai permulaan untuk tumbuh, berbagi, dan membangun kehidupan bersama.',
    },
  ],
  liveStream: {
    enabled: true,
    platformUrl: 'https://youtube.com/live/argakirana',
    date: 'Minggu, 14 Februari 2027',
    time: '09:00',
    timezone: 'WIB',
  },
};

export const EVENTS_DATA: EventDetail[] = [
  {
    id: 'akad',
    type: 'akad',
    title: 'Akad Nikah',
    badge: '01',
    badgeBg: 'bg-[#cc3a63]',
    badgeText: 'text-white',
    date: 'Minggu, 14 Februari 2027',
    time: '09:00 WIB',
    locationName: 'Graha Manggala Siliwangi',
    address: 'Jl. Aceh No. 66, Merdeka, Kota Bandung, Jawa Barat',
    mapsUrl: 'https://maps.google.com/maps?q=Graha+Manggala+Siliwangi+Bandung',
  },
  {
    id: 'resepsi',
    type: 'resepsi',
    title: 'Resepsi',
    badge: '02',
    badgeBg: 'bg-[#a2ab73]',
    badgeText: 'text-[#2b2620]',
    date: 'Minggu, 14 Februari 2027',
    time: '11:00 WIB',
    locationName: 'Graha Manggala Siliwangi',
    address: 'Jl. Aceh No. 66, Merdeka, Kota Bandung, Jawa Barat',
    mapsUrl: 'https://maps.google.com/maps?q=Graha+Manggala+Siliwangi+Bandung',
  },
];

export const GALLERY_PHOTOS: GalleryPhoto[] = [
  {
    id: 'photo-1',
    title: 'Bergandengan tangan di bawah lampu taman',
    src: '/assets/gallery/gallery-1.svg',
    alt: 'Ilustrasi: bergandengan tangan di bawah lampu taman',
    rotation: '-rotate-2',
  },
  {
    id: 'photo-2',
    title: 'Balon hati di hari yang cerah',
    src: '/assets/gallery/gallery-2.svg',
    alt: 'Ilustrasi: balon hati di hari yang cerah',
    rotation: 'rotate-2',
  },
  {
    id: 'photo-3',
    title: 'Piknik berdua',
    src: '/assets/gallery/gallery-3.svg',
    alt: 'Ilustrasi: piknik berdua',
    rotation: '-rotate-1',
  },
  {
    id: 'photo-4',
    title: 'Berbagi payung saat hujan',
    src: '/assets/gallery/gallery-4.svg',
    alt: 'Ilustrasi: berbagi payung saat hujan',
    rotation: 'rotate-2',
  },
  {
    id: 'photo-5',
    title: 'Kotak cincin lamaran',
    src: '/assets/gallery/gallery-5.svg',
    alt: 'Ilustrasi: kotak cincin lamaran',
    rotation: '-rotate-2',
  },
  {
    id: 'photo-6',
    title: 'Senja di tepi pantai',
    src: '/assets/gallery/gallery-6.svg',
    alt: 'Ilustrasi: senja di tepi pantai',
    rotation: 'rotate-1',
  },
  {
    id: 'photo-7',
    title: 'Dua cangkir kopi',
    src: '/assets/gallery/gallery-7.svg',
    alt: 'Ilustrasi: dua cangkir kopi',
    rotation: '-rotate-1',
  },
  {
    id: 'photo-8',
    title: 'Surat cinta dan bunga',
    src: '/assets/gallery/gallery-8.svg',
    alt: 'Ilustrasi: surat cinta dan bunga',
    rotation: 'rotate-2',
  },
  {
    id: 'photo-9',
    title: 'Potret berdua dalam bingkai bunga',
    src: '/assets/gallery/gallery-9.svg',
    alt: 'Ilustrasi: potret berdua dalam bingkai bunga',
    rotation: '-rotate-2',
  },
  {
    id: 'photo-10',
    title: 'Simpan tanggalnya',
    src: '/assets/gallery/gallery-10.svg',
    alt: 'Ilustrasi: simpan tanggalnya',
    rotation: 'rotate-1',
  },
];

export const BANK_ACCOUNTS: BankAccount[] = [
  {
    id: 'bca',
    bankName: 'BCA',
    accountNumber: '9876543210',
    holderName: 'a.n. Kirana Maharani Putri',
    badgeBg: 'bg-[#fcecf0]',
    badgeText: 'text-[#cc3a63]',
    btnBg: 'bg-[#cc3a63]',
    btnText: 'text-white',
  },
];

export const INITIAL_WISHES: Wish[] = [
  {
    id: 'w-1',
    name: 'Budi & Maya',
    status: 'Hadir',
    message: "Barakallahu lakuma wa baraka 'alaikuma wa jama'a bainakuma fii khair. Selamat menempuh hidup baru Arga & Kirana! Bahagia selamanya ❤️",
    createdAt: 'Baru saja',
    guestCount: 2,
  },
  {
    id: 'w-2',
    name: 'Dinda Lestari',
    status: 'Hadir',
    message: 'Selamat Kirana & Kak Arga! Semoga menjadi keluarga yang sakinah mawaddah warahmah, lancar acaranya sampai hari H! 🌸',
    createdAt: '15 menit lalu',
    guestCount: 1,
  },
  {
    id: 'w-3',
    name: 'Reno Pratama',
    status: 'Hadir',
    message: 'Congrats bro Arga & Kirana! Turut berbahagia untuk kalian berdua. See you on the big day!',
    createdAt: '1 jam lalu',
    guestCount: 2,
  },
];

export const DEFAULT_VIDEO_CONFIG: VideoConfig = {
  directVideoUrl: DEFAULT_VIDEO_URL,
  youtubeUrl: 'https://www.youtube.com/watch?v=ysz5S6PUM-U',
  embedUrl: DEFAULT_VIDEO_URL,
  title: 'Video Prewedding',
  subtitle: 'Momen manis dan hangat perjalanan cinta Kirana & Arga.',
};

export const PRESET_VIDEOS = [
  {
    label: 'Kisah Kami — animasi doodle (Video Bawaan)',
    url: DEFAULT_VIDEO_URL,
  },
  {
    label: 'Cinematic Prewedding Outdoor Nature',
    url: 'https://www.youtube.com/watch?v=ysz5S6PUM-U',
  },
  {
    label: 'Romantic Minimalist Studio',
    url: 'https://www.youtube.com/watch?v=L_LUpnjgPso',
  },
];

const palette = (prefix: string, colors: [string, string][]): DressCodeColor[] =>
  colors.map(([name, hex], i) => ({ id: `${prefix}-${i + 1}`, name, hex }));

// Ready-made palettes offered in the CMS dress code editor.
export const DRESS_CODE_PRESETS: { id: string; label: string; colors: DressCodeColor[] }[] = [
  {
    id: 'terracotta-sage',
    label: 'Terracotta & Sage (senada tema)',
    colors: palette('ts', [['Terracotta', '#B4533C'], ['Dusty Peach', '#E8B4A4'], ['Sage', '#A9BFA0'], ['Cream', '#EFE3C6'], ['Mocha', '#6B4F3F']]),
  },
  {
    id: 'dusty-rose',
    label: 'Dusty Rose',
    colors: palette('dr', [['Dusty Rose', '#C98A8F'], ['Blush', '#E9C6C3'], ['Nude', '#F3E6DC'], ['Taupe', '#B7A6A1'], ['Mauve', '#7E5A62']]),
  },
  {
    id: 'earth-tone',
    label: 'Earth Tone',
    colors: palette('et', [['Cokelat Kayu', '#8B5E3C'], ['Camel', '#C49A6C'], ['Pasir', '#D9C3A5'], ['Olive', '#7C8363'], ['Espresso', '#4A3B2F']]),
  },
  {
    id: 'navy-gold',
    label: 'Navy & Gold',
    colors: palette('ng', [['Navy', '#1F2A44'], ['Biru Baja', '#3C5A80'], ['Emas', '#C9A45C'], ['Champagne', '#E8DCC2'], ['Ivory', '#F7F3EA']]),
  },
  {
    id: 'pastel-garden',
    label: 'Pastel Garden',
    colors: palette('pg', [['Baby Blue', '#BFD8E9'], ['Pink Pastel', '#F5C9D4'], ['Mint', '#D8E9C9'], ['Butter', '#F6E7B4'], ['Lavender', '#D9CCE8']]),
  },
];

export const DEFAULT_DRESS_CODE: DressCodeConfig = {
  enabled: true,
  attire: 'Semi Formal · Batik / Kebaya Modern',
  description:
    'Kami akan sangat bahagia bila Bapak/Ibu/Saudara/i berkenan mengenakan busana dengan nuansa warna berikut.',
  colors: DRESS_CODE_PRESETS[0].colors,
  avoidColors: [{ id: 'avoid-1', name: 'Putih', hex: '#FFFFFF' }],
  notes: [
    'Warna putih kami khususkan untuk pengantin',
    'Kenakan busana yang sopan dan nyaman',
    'Aksesori bernuansa senada sangat dipersilakan',
  ],
};

export const DEFAULT_GIFT_ADDRESS = 'Graha Manggala Siliwangi, Jl. Aceh No. 66, Merdeka, Kota Bandung, Jawa Barat';

export function extractYouTubeId(url: string): string | null {
  if (!url) return null;
  const cleanUrl = url.trim();
  const regExp = /(?:youtube\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?|shorts)\/|.*[?&]v=)|youtu\.be\/)([^"&?\/\s]{11})/;
  const match = cleanUrl.match(regExp);
  if (match && match[1]) {
    return match[1];
  }
  if (cleanUrl.length === 11 && !cleanUrl.includes('/') && !cleanUrl.includes('.')) {
    return cleanUrl;
  }
  return null;
}
